server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql:///oa
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hufan1998
  mail:
    username: 787386451@qq.com
    password: dxslnfxoeqeubeie
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  thymeleaf:
    encoding: utf-8
    cache: false
    mode: LEGACYHTML5
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 20MB
mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: org.java.entity



