server:
  port: 9999

spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql:///hk
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

  datasource:
    url: jdbc:mysql:///hk
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root


